version: '3.7'

services:
  postgres:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db_postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  cassandra:
    image: cassandra:3.11
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
    ports:
      - 9042:9042
    volumes:
      - ./cassandra:/var/lib/cassandra

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mariadb
    ports:
      - 3307:3306
    volumes:
      - ./mariadb:/var/lib/mysql

  node-red:
    image: nodered/node-red
    restart: always
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data
  